#pragma once
#include <Arduino.h>

namespace mixduino {

class Board {
public:
  enum Event {
    LeftPlay = 100,
    LeftCue,
    LeftSync,
    LeftLoop,
    LeftMode,
    LeftPad1,
    LeftPad2,
    LeftPad3,
    LeftPad4,
    LeftPad5,
    LeftPad6,
    LeftPad7,
    LeftPad8,
    LeftTempo,
    RightPlay = 200,
    RightCue,
    RightSync,
    RightLoop,
    RightMode,
    RightPad1,
    RightPad2,
    RightPad3,
    RightPad4,
    RightPad5,
    RightPad6,
    RightPad7,
    RightPad8,
    RightTempo,
    DeckAGain = 300,
    DeckATreb,
    DeckAMid,
    DeckABas,
    DeckAFiltr,
    DeckAVolume,
    DeckAMonCue,
    DeckBGain,
    DeckBTreb,
    DeckBMid,
    DeckBBas,
    DeckBFiltr,
    DeckBVolume,
    DeckBMonCue,
    DeckCGain,
    DeckCTreb,
    DeckCMid,
    DeckCBas,
    DeckCFiltr,
    DeckCVolume,
    DeckCMonCue,
    MasterVol,
    MonitorVol,
    MonitorMix,
    Fx1Pot1 = 400,
    Fx1Pot2,
    Fx1Pot3,
    Fx1Btn1,
    Fx1Btn2,
    Fx1Btn3,
    Fx2Pot1,
    Fx2Pot2,
    Fx2Pot3,
    Fx2Btn1,
    Fx2Btn2,
    Fx2Btn3,
    BrowserBackBtn = 500,
    BrowserPrevBtn,
    BrowserLeftEnc,
    BrowserLeftBtn,
    BrowserRightEnc,
    BrowserRightBtn,
    TouchBarLeft = 600,
    TouchBarRight,
    SwitchDeck = 700,
    Shift
  };
};

} // namespace mixduino