#pragma once
#include <Arduino.h>

namespace mixduino {

class Board {
public:
  enum Event {
    evLeftPlay = 100,
    evLeftCue,
    evLeftSync,
    evLeftLoop,
    evLeftMode,
    evLeftPad1,
    evLeftPad2,
    evLeftPad3,
    evLeftPad4,
    evLeftPad5,
    evLeftPad6,
    evLeftPad7,
    evLeftPad8,
    evLeftTempo,
    evRightPlay = 200,
    evRightCue,
    evRightSync,
    evRightLoop,
    evRightMode,
    evRightPad1,
    evRightPad2,
    evRightPad3,
    evRightPad4,
    evRightPad5,
    evRightPad6,
    evRightPad7,
    evRightPad8,
    evRightTempo,
    evDeckAGain = 300,
    evDeckATreb,
    evDeckAMid,
    evDeckABas,
    evDeckAFiltr,
    evDeckAVolume,
    evDeckAMonCue,
    evDeckBGain,
    evDeckBTreb,
    evDeckBMid,
    evDeckBBas,
    evDeckBFiltr,
    evDeckBVolume,
    evDeckBMonCue,
    evDeckCGain,
    evDeckCTreb,
    evDeckCMid,
    evDeckCBas,
    evDeckCFiltr,
    evDeckCVolume,
    evDeckCMonCue,
    evMasterVol,
    evMonitorVol,
    evMonitorMix,
    evFx1Pot1 = 400,
    evFx1Pot2,
    evFx1Pot3,
    evFx1Btn1,
    evFx1Btn2,
    evFx1Btn3,
    evFx2Pot1,
    evFx2Pot2,
    evFx2Pot3,
    evFx2Btn1,
    evFx2Btn2,
    evFx2Btn3,
    evBrwsBackBtn = 500,
    evBrwsPrevBtn,
    evBrwsLeftEnc,
    evBrwsLeftBtn,
    evBrwsRightEnc,
    evBrwsRightBtn,
    evTouchBarLeft = 600,
    evTouchBarRight,
    evSwitchDeck = 700,
    evShift
  };
};

} // namespace mixduino